name: CI

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: ci_test
    outputs:
      semver: ${{steps.semver.outputs.version_tag}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"
        id: semver
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0

      - name: Install namedreturns linter
        run: go install github.com/nikogura/namedreturns@latest

      - name: Run namedreturns linter
        run: namedreturns ./...

      - name: Run Tests
        run: |
          go test -v ./...

      - name: Tag Repo
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{steps.semver.outputs.version_tag}}
          tag_prefix: ""

      - name: Publish Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semver.outputs.version_tag }}
          name: v${{ steps.semver.outputs.version_tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}      

